export const FORM_IDENTIFIERS = {
	nameAttribute: "identifier",
	createMachine: "create-machine",
	deleteMachine: "delete-machine",
	updateMachine: "update-machine",
	updateMachiningAmendment: "update-machining-amendment",
	updateProcessDefinitionCategory: "update-process-definition-category",
	createStitchingModifier: "create-stitching-modifier",
	deleteStitchingModifier: "delete-stitching-modifier",
	updateStitchingModifier: "update-stitching-modifier",
	updateStitchingCharacteristics: "update-stitching-characteristics",
	updateStitchingFolding: "update-stitching-folding",
	createProcessClass: "create-process-class",
	deleteProcessClass: "delete-process-class",
	updateProcessClass: "update-process-class",
	createProcessType: "create-process-type",
	deleteProcessType: "delete-process-type",
	updateProcessType: "update-process-type",
	completeProcessQuestions: "complete-process-questions",
	partialSaveProcessQuestions: "partial-save-process-questions",
	createDesignDepartment: "create-style-department",
} as const;
