export const QUERY_KEYS = {
	actions: "actions",
	action: "action",
	action_in_use: "action_in_use",
	steps: "steps",
	stepsNM: "stepsNM",
	step: "step",
	step_in_use: "step_in_use",
	is_admin: "is_admin",
	process: "process",
	process_in_use: "operation_in_use",
	processes: "processes",
	process_file: "process_file",
	processes_filtered: "operations_filtered",
	process_categories: "process_categories",
	process_class_in_use: "operation_class_in_use",
	process_classes: "process_classes",
	process_definitions: "process_definitions",
	process_definition: "process_definition",
	process_definition_in_use: "process_definition_in_use",
	process_sets: "process_sets",
	process_set: "process_set",
	process_type_in_use: "operation_type_in_use",
	process_types: "process_types",
	process_definition_categories: ["process_definition", "categories"],
	process_definition_task_formulas: ["process_definition", "task_formulas"],
	path_files: "path_files",
	designs: "designs",
	design: "design",
	design_file: "design_file",
	design_departments: "design_departments",
	design_department: "design_department",
	settings_cutting_steps: ["settings", "cutting", "steps"],
	settings_cutting_process_definitions_default_cutting: [
		"settings",
		"cutting",
		"process_definitions",
		"default_cutting",
	],
	settings_departments: ["settings", "departments"],
	settings_department_in_use: "settings_department_in_use",
	settings_general: ["settings", "general"],
	settings_grades: ["settings", "grades"],
	settings_grade_in_use: "settings_grade_in_use",
	settings_machining_amendments: ["settings", "machining", "amendments"],
	settings_machining_steps: ["settings", "machining", "steps"],
	settings_machining_machines: ["settings", "machining", "machines"],
	settings_machining_machine_in_use: "settings_machining_machine_in_use",
	settings_machining_process_definitions_machining: [
		"settings",
		"machining",
		"process_definitions",
		"machining",
	],
	settings_machining_process_definitions_path_features: [
		"settings",
		"machining",
		"process_definitions",
		"path_features",
	],
	settings_machining_process_definitions_path_feature_in_use:
		"settings_machining_process_definitions_path_feature_in_use",
	settings_machining_stitching_characteristics: [
		"settings",
		"machining",
		"stitching_characteristics",
	],
	settings_machining_stitching_modifiers: [
		"settings",
		"machining",
		"stitching_modifiers",
	],
	settings_machining_stitching_modifier_in_use:
		"settings_machining_stitching_modifier_in_use",
	system_cutting_methods_natural: ["system", "cutting_methods", "natural"],
	system_cutting_methods_synthetic: [
		"system",
		"cutting_methods",
		"synthetic",
	],
	system_cutting_types: ["system", "cutting_types"],
	system_feed_systems: ["system", "feed_systems"],
	system_material_types: ["system", "material_types"],
	system_machining_stitching_modifiers: [
		"system",
		"machining",
		"stitching_modifiers",
	],
	system_units: ["system", "units"],
	audit_list: "audit_list",
} as const;
